# Generated by Django 5.1.1 on 2024-09-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_updated_post_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
    ]
